### ISSUE TITLE
mounting overlayfs

### ISSUE THREAD

**Issue by adrenalinco** [colinoflynn/raymarine-axiom-rescue#1]
sudo mount -t overlay -o lowerdir=fin,upperdir=to,workdir=temp overlay fin
should be 
sudo mount -t overlay -o lowerdir=fm,upperdir=to,workdir=temp overlay fin
i guess ?

**Comment by colinoflynn** [comment]
Oops! Yup, I was manually copying commands as for some reason copy/paste on my VM broke right as I went to do that. The stackexchange post had the correct sequence, hopefully that was only error.
